name: Build, Scan, Push to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin 320060061347.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t portfolio .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan image
        run: |
          trivy image  portfolio

      - name: Tag image
        run: |
          docker tag portfolio \
          320060061347.dkr.ecr.eu-north-1.amazonaws.com/portfolio:latest

      - name: Push to ECR
        run: |
          docker push 320060061347.dkr.ecr.eu-north-1.amazonaws.com/portfolio:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_NEW}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_N }}
          script: |
            cd /home/ec2-user

            aws ecr get-login-password --region eu-north-1 | \
            docker login --username AWS --password-stdin 320060061347.dkr.ecr.eu-north-1.amazonaws.com

            docker compose pull
            docker compose up -d --force-recreate
      

     
