name: Build, Scan, Push and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 320060061347.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t portfolio .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan image
        run: |
          trivy image --severity CRITICAL,HIGH --exit-code 1 portfolio

      - name: Tag image
        run: |
          docker tag portfolio \
          320060061347.dkr.ecr.eu-north-1.amazonaws.com/portfolio:latest

      - name: Push to ECR
        run: |
          docker push 320060061347.dkr.ecr.eu-north-1.amazonaws.com/portfolio:latest

     
